name: 'Add Eyes Reaction'
description: 'Adds an eyes reaction to the current issue or pull request'
author: 'pelikhan'

inputs:
  token:
    description: GitHub token or PAT with the permissions this action needs
    default: ${{ github.token }}
    required: false
  reaction:
    description: 'Type of reaction to add (defaults to eyes)'
    required: false
    default: 'eyes'

runs:
  using: 'composite'
  steps:
    - name: Add reaction
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        REACTION: ${{ inputs.reaction }}
      run: |
        echo "Event path: $GITHUB_EVENT_PATH"
        echo "Event name: $GITHUB_EVENT_NAME"
        echo "Event content:"
        cat "$GITHUB_EVENT_PATH" | jq '.'

        # Try to extract the comment ID from issue_comment events
        if jq -e '.comment.id' "$GITHUB_EVENT_PATH" > /dev/null 2>&1; then
          COMMENT_ID=$(jq -r '.comment.id' "$GITHUB_EVENT_PATH")
          NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
          
          if [[ ! -z "$COMMENT_ID" && ! -z "$NUMBER" ]]; then
            echo "Adding $REACTION reaction to comment $COMMENT_ID on issue #$NUMBER"
            gh api \
              --method POST \
              repos/$GITHUB_REPOSITORY/issues/comments/$COMMENT_ID/reactions \
              -f content="${REACTION}"
            exit 0
          fi
        fi

        if jq -e '.issue.number' "$GITHUB_EVENT_PATH" > /dev/null 2>&1; then
          NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
          TYPE="issues"
        elif jq -e '.pull_request.number' "$GITHUB_EVENT_PATH" > /dev/null 2>&1; then
          NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
          TYPE="issues"
        elif [[ "$GITHUB_EVENT_NAME" == "pull_request_target" ]] && jq -e '.pull_request.number' "$GITHUB_EVENT_PATH" > /dev/null 2>&1; then
          # Handle pull_request_target events, which have the same structure as pull_request events
          NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
          TYPE="issues"
        elif jq -e '.number' "$GITHUB_EVENT_PATH" > /dev/null 2>&1; then
          NUMBER=$(jq -r '.number' "$GITHUB_EVENT_PATH")
          # Determine if this is an issue or PR based on presence of pull_request field
          if jq -e '.pull_request' "$GITHUB_EVENT_PATH" > /dev/null 2>&1; then
            TYPE="issues"
          else
            TYPE="issues"
          fi
        fi
        
        # Fallback to issue_number or pr_number inputs if available
        if [[ -z "$NUMBER" || "$NUMBER" == "$GITHUB_REF" ]]; then
          echo "Could not determine issue or PR number from context."
          exit 1
        fi
        
        echo "Adding $REACTION reaction to $GITHUB_REPOSITORY $TYPE #$NUMBER"
        
        gh api \
          --method POST \
          repos/$GITHUB_REPOSITORY/$TYPE/$NUMBER/reactions \
          -f content="${REACTION}" \
          --verbose

branding:
  icon: 'eye'
  color: 'blue'
