name: 'Add Eyes Reaction'
description: 'Adds an eyes reaction to the current issue or pull request, then removes it at the end'
author: 'pelikhan'

inputs:
  token:
    description: GitHub token or PAT with the permissions this action needs
    default: ${{ github.token }}
    required: false
  reaction:
    description: 'Type of reaction to add (defaults to eyes)'
    required: false
    default: 'eyes'

runs:
  using: 'composite'
  steps:
    - name: Add reaction
      id: add-reaction
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        REACTION: ${{ inputs.reaction }}
      run: |
        echo "Event path: $GITHUB_EVENT_PATH"
        echo "Event name: $GITHUB_EVENT_NAME"
        cat "$GITHUB_EVENT_PATH" | jq '.'

        if jq -e '.comment.id' "$GITHUB_EVENT_PATH" > /dev/null 2>&1; then
          COMMENT_ID=$(jq -r '.comment.id' "$GITHUB_EVENT_PATH")
          NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
          if [[ -n "$COMMENT_ID" && -n "$NUMBER" ]]; then
            echo "Adding $REACTION reaction to comment $COMMENT_ID"
            REACTION_RESPONSE=$(gh api \
              --method POST \
              repos/$GITHUB_REPOSITORY/issues/comments/$COMMENT_ID/reactions \
              -f content="${REACTION}")
            echo "$REACTION_RESPONSE" | jq '.' > reaction.json
            echo "reaction_id=$(jq -r '.id' reaction.json)" >> $GITHUB_OUTPUT
            exit 0
          fi
        fi

        if jq -e '.issue.number' "$GITHUB_EVENT_PATH" > /dev/null 2>&1; then
          NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
        elif jq -e '.pull_request.number' "$GITHUB_EVENT_PATH" > /dev/null 2>&1; then
          NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
        elif jq -e '.number' "$GITHUB_EVENT_PATH" > /dev/null 2>&1; then
          NUMBER=$(jq -r '.number' "$GITHUB_EVENT_PATH")
        fi

        if [[ -z "$NUMBER" ]]; then
          echo "Could not determine issue or PR number."
          exit 1
        fi

        echo "Adding $REACTION reaction to issue/PR #$NUMBER"
        REACTION_RESPONSE=$(gh api \
          --method POST \
          repos/$GITHUB_REPOSITORY/issues/$NUMBER/reactions \
          -f content="${REACTION}")
        echo "$REACTION_RESPONSE" | jq '.' > reaction.json
        echo "reaction_id=$(jq -r '.id' reaction.json)" >> $GITHUB_OUTPUT

    - name: Remove reaction
      if: always()
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        if [[ -f reaction.json ]]; then
          REACTION_ID=$(jq -r '.id' reaction.json)
          echo "Removing reaction with ID $REACTION_ID"
          gh api \
            --method DELETE \
            repos/$GITHUB_REPOSITORY/reactions/$REACTION_ID
        else
          echo "No reaction.json file found. Skipping removal."
        fi
